openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/users/{username}/:
    get:
      tags:
      - user-controller
      operationId: getUser
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/User"
    put:
      tags:
      - user-controller
      operationId: putUser
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdate"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
    delete:
      tags:
      - user-controller
      operationId: deleteUser
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/users/:
    get:
      tags:
      - user-controller
      operationId: getUsers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDto"
    post:
      tags:
      - user-controller
      operationId: postUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/users/generate/{cantidad}/:
    get:
      tags:
      - user-controller
      operationId: generateUsers
      parameters:
      - name: cantidad
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    UserUpdate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        gender:
          type: string
    UserCreate:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        email:
          type: string
        gender:
          type: string
    User:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        email:
          type: string
        gender:
          type: string
        picture:
          type: string
    UserDto:
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        email:
          type: string
        gender:
          type: string
        picture:
          type: string
