version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: challengebd
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Permite que el usuario root no tenga contraseña
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: